version: "3.9"

services:
  backend:
    build: ./backend
    tty: true
    ports:
      - 8000:8000
      - "9229:9229"
    volumes:
      - ./backend:/usr/src/app:rw

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
